FROM python:latest

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

COPY pyproject.toml poetry/lock ./

RUN poetry config virtualenvs.create false &&  poetry install --no-dev

COPY . .

CMD [ "python", "main.py" ]