FROM python:3.12.7


WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_OFF=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=on

COPY ../../app .

RUN pip install --upgrade pip && \
    pip install --no-cache-dir --upgrade -r requirements.txt
    

RUN chmod +x ../../app/entrypoint.sh

ENTRYPOINT [ "../../app/entrypoint.sh" ]